djangoerp/core/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'


from django.conf.urls import url
from django.views.generic import TemplateView

from .views import *


urlpatterns = [

    # User authentication management.
    url(r'^users/login/$', 'django.contrib.auth.views.login', {'template_name': 'auth/login.html'}, name='user_login'),
    url(r'^users/logout/$', view='django.contrib.auth.views.logout_then_login', name='user_logout'),
    url(r'^users/(?P<pk>\d+)/$', view=DetailUserView.as_view(), name='user_detail'),
    url(r'^users/(?P<pk>\d+)/edit/$', view=UpdateUserView.as_view(), name='user_edit'),
    url(r'^users/(?P<pk>\d+)/delete/$', view=DeleteUserView.as_view(), name='user_delete'),
    
    # Homepage.
    url(r'^$', TemplateView.as_view(template_name="index.html")),
]

djangoerp/menus/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'

from django.conf.urls import *

from .views import *

urlpatterns = [

    url(r'^bookmarks/$', view=ListBookmarkView.as_view(), name='bookmark_list'),
    url(r'^bookmarks/add/$', view=CreateBookmarkView.as_view(), name='bookmark_add'),
    url(r'^bookmarks/(?P<slug>[-\w]+)/edit/$', view=UpdateBookmarkView.as_view(), name='bookmark_edit'),
    url(r'^bookmarks/(?P<slug>[-\w]+)/delete/$', view=DeleteBookmarkView.as_view(), name='bookmark_delete'),
]

djangoerp/pluggets/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'


from django.conf.urls import url

from .views import *


urlpatterns = [

    url(r'^pluggets/add/(?P<slug>[-\w]+)/$', view=PluggetWizard.as_view(PluggetWizard.DEFAULT_FORMS), name='plugget_add'),
    url(r'^pluggets/(?P<pk>[\d]+)/edit/$', view=PluggetWizard.as_view(PluggetWizard.DEFAULT_FORMS), name='plugget_edit'),
    url(r'^pluggets/(?P<pk>[\d]+)/delete/$', view=DeletePluggetView.as_view(), name='plugget_delete'),
]

djangoerp/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'


from django.conf.urls import url, include
from django.conf import settings
from django.apps import apps as app_registry


urlpatterns = []


def has_urls(app):
    if app:
        try:
            return getattr(app, 'urls', None) or  __import__("%s.urls" % app.name, {}, {}, ["*"])
        except ImportError:
            pass
    return False


# Basic URL patterns bootstrap.
if 'django.contrib.admin' in settings.INSTALLED_APPS:
    if 'django.contrib.admindocs' in settings.INSTALLED_APPS:
        urlpatterns += [
            url(r'^admin/doc/', include('django.contrib.admindocs.urls'))
        ]
    from django.contrib import admin
    admin.autodiscover()
    urlpatterns += [
        url(r'^admin/', include(admin.site.urls))
    ]

if 'django.contrib.staticfiles' in settings.INSTALLED_APPS:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()


urlpatterns += [url(r'^', include('%s.urls' % app.name)) for app in app_registry.get_app_configs() if has_urls(app)]

djangoerp/pluggets/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'


from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.text import slugify
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.utils.translation import ugettext_lazy as _
from djangoerp.core.models import validate_json


@python_2_unicode_compatible
class Region(models.Model):
    """A logical area that could host any kind of Pluggets.
    
    A region could have a 1-1 relation with a specific object (i.e. dashboards).
    """
    slug = models.SlugField(max_length=100, unique=True, verbose_name=_('slug'))
    title = models.CharField(max_length=256, blank=True, null=True, verbose_name=_('title'))
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    owner_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        verbose_name = _('region')
        verbose_name_plural = _('regions')

    def __str__(self):
        return self.title or self.slug

    def get_absolute_url(self):
        try:
            from django.contrib.auth import get_user_model
            if not isinstance(self.owner_object, get_user_model()):
                return self.owner_object.get_absolute_url()
        except AttributeError:
            pass
        return "/"

@python_2_unicode_compatible
class Plugget(models.Model):
    """A plugget is a graphical element hosted on a Region.
    """
    region = models.ForeignKey(Region, related_name='pluggets', verbose_name=_('region'))
    title = models.CharField(max_length=100, verbose_name=_('title'))
    description = models.TextField(blank=True, null=True, verbose_name=_('description'))
    source = models.CharField(max_length=256, verbose_name=_('source'))
    template = models.CharField(max_length=256, default="pluggets/base_plugget.html", verbose_name=_('template'))
    context = models.TextField(blank=True, null=True, validators=[validate_json], help_text=_('Use the JSON syntax.'), verbose_name=_('context'))
    sort_order = models.PositiveIntegerField(default=0, verbose_name=_('sort order'))

    class Meta:
        ordering = ('region', 'sort_order', 'title',)
        verbose_name = _('plugget')
        verbose_name_plural = _('pluggets')
        unique_together = ('region', 'title')

    def __str__(self):
        return "%s | %s" % (self.region, self.title)
        
    def slug(self):
        return slugify("%s_%s" % (self.region, self.title))

    def get_absolute_url(self):
        return self.region.get_absolute_url()

    @models.permalink
    def get_edit_url(self):
        return ('plugget_edit', (), {"pk": self.pk})

    @models.permalink
    def get_delete_url(self):
        return ('plugget_delete', (), {"pk": self.pk})

djangoerp/menus/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'

from django import forms
from django.utils.translation import ugettext_lazy as _
from djangoerp.core.forms import enrich_form

from .models import Menu, Bookmark

class BookmarkForm(forms.ModelForm):
    """Form for bookmark data.
    """
    class Meta:
        model = Bookmark
        fields = ['title', 'url', 'description', 'new_window']
    
    def __init__(self, *args, **kwargs):
        self.menu = kwargs.pop("menu", None)
        super(BookmarkForm, self).__init__(*args, **kwargs)
        if not self.menu:
            try:
                if self.instance and self.instance.menu:
                    self.menu = self.instance.menu
            except Menu.DoesNotExist:
                pass
    
    def clean_title(self):
        title = self.cleaned_data['title']
       
        try:
            bookmark = Bookmark.objects.get(title=title, menu=self.menu)
            if bookmark != self.instance:
                raise forms.ValidationError(_("This title is already in use."))
                
        except Bookmark.DoesNotExist:
            pass
            
        return title
        
    def save(self, commit=True):
        from django.template.defaultfilters import slugify
        
        obj = super(BookmarkForm, self).save(commit=False)
        obj.menu = self.menu or obj.menu
        obj.slug = slugify(("%s_%s" % (obj.title, self.menu.slug))[:-1])
        
        if commit:
            obj.save()
            
        return obj

enrich_form(BookmarkForm)

djangoerp/menus/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'

from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from djangoerp.core.utils import clean_http_referer
from djangoerp.core.views import SetCancelUrlMixin, ModelListView
from djangoerp.core.decorators import obj_permission_required as permission_required

from .utils import get_bookmarks_for
from .models import *
from .forms import *

def _get_bookmarks(request, *args, **kwargs):
    return get_bookmarks_for(request.user.username)

def _get_bookmark(request, *args, **kwargs):
    bookmarks = _get_bookmarks(request, *args, **kwargs)
    return get_object_or_404(Bookmark, slug=kwargs.get('slug', None), menu=bookmarks)
    
class BookmarkMixin(object):
    model = Bookmark
    
    def get_queryset(self):
        qs = super(BookmarkMixin, self).get_queryset()
        return qs.filter(menu=_get_bookmarks(self.request, self.args, self.kwargs))
    
class BookmarkCreateUpdateMixin(SuccessMessageMixin, SetCancelUrlMixin, BookmarkMixin):
    form_class = BookmarkForm

    def get_form_kwargs(self):
        menu =  _get_bookmarks(self.request, *self.args, **self.kwargs)
        kwargs = super(BookmarkCreateUpdateMixin, self).get_form_kwargs()
        kwargs['menu'] = menu
        return kwargs        
    
    def get_initial(self):
        initial = super(BookmarkCreateUpdateMixin, self).get_initial() 
        url = clean_http_referer(self.request)
        
        self.cancel_url = url
        
        if not self.object:
            initial["url"] = url
                
        return initial
    
class ListBookmarkView(BookmarkMixin, ModelListView):
    field_list = ["title", "url", "description", "new_window"]
    delete_template_name = "menus/bookmark_model_list_confirm_delete.html"
    paginate_by=10
    
    @method_decorator(permission_required("menus.view_menu", _get_bookmarks))
    def dispatch(self, request, *args, **kwargs):
        return super(ListBookmarkView, self).dispatch(request, *args, **kwargs)
    
class CreateBookmarkView(BookmarkCreateUpdateMixin, CreateView):
    success_message = _("The bookmark was created successfully.")
    
    @method_decorator(permission_required("menus.change_menu", _get_bookmarks))
    @method_decorator(permission_required("menus.add_link"))
    def dispatch(self, request, *args, **kwargs):
        return super(CreateBookmarkView, self).dispatch(request, *args, **kwargs)
    
class UpdateBookmarkView(BookmarkCreateUpdateMixin, UpdateView):
    success_url = reverse_lazy("bookmark_list")
    success_message = _("The bookmark was updated successfully.")
    
    @method_decorator(permission_required("menus.change_menu", _get_bookmarks))
    @method_decorator(permission_required("menus.change_link", _get_bookmark))
    def dispatch(self, request, *args, **kwargs):
        return super(UpdateBookmarkView, self).dispatch(request, *args, **kwargs)
        
class DeleteBookmarkView(SuccessMessageMixin, SetCancelUrlMixin, BookmarkMixin, DeleteView):
    success_url = reverse_lazy("bookmark_list")
    success_message = _("The bookmark was deleted successfully.")
    
    @method_decorator(permission_required("menus.change_menu", _get_bookmarks))
    @method_decorator(permission_required("menus.delete_link", _get_bookmark))
    def dispatch(self, request, *args, **kwargs):
        return super(DeleteBookmarkView, self).dispatch(request, *args, **kwargs)

djangoerp/themes/default/templates/pluggets/base_plugget.html
{% load i18n %}
{% load perms %}

<aside class="plugget{% if plugget_index and not plugget_index|divisibleby:"2" %} altplugget{% endif %} {{ plugget.slug }}" id="{{ plugget.slug }}-plugget">
    <header>
        <h3>{% if plugget.title %}{% trans plugget.title %}{% else %}{% trans plugget.template.title %}{% endif %}</h3>
        <ul class="actions">
        {% if plugget.region|user_has_perm:"pluggets.change_region" %}
            {% if plugget|user_has_perm:"pluggets.change_plugget" %}
            <li class="edit"><a title="{% trans 'Edit' %}"  href="{{ plugget.get_edit_url }}">{% trans "Edit" %}</a></li>
            {% endif %}
            {% if plugget|user_has_perm:"pluggets.delete_plugget" %}
            <li class="delete"><a title="{% trans 'Delete' %}"  href="{{ plugget.get_delete_url }}">{% trans "Delete" %}</a></li>
            {% endif %}
        {% endif %}
        </ul>
    </header>
    {% block plugget-body %}
    <section class="body">
        {% block plugget-content %}{% trans text %}{% endblock %}
        {% if not text %}{% include "elements/empty.html" %}{% endif %}
    </section>
    {% endblock %}
</aside>

djangoerp/themes/default/templates/pluggets/dashboard.html
{% extends "pluggets/region.html" %}

{% load i18n %}
{% load perms %}

{% block region-header %}
<div class="dashboard">
    {{ block.super }}
{% endblock %}

{% block region-footer %}
    {{ block.super }}
    <div class="empty{% if not region.pluggets.count|divisibleby:"2" %} altrow{% endif %}">
        <ul class="actions">
            {% if region|user_has_perm:"pluggets.change_region" and perms.pluggets.add_plugget %}
            <li class="add"><a title="{% trans 'Add plugget' %}" href="{% url 'plugget_add' region.slug %}">{% trans 'Add' %}</a> {% trans "Click to add a plugget." %}</li>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

djangoerp/themes/default/templates/pluggets/menu.html
{% load menus %}

{% render_menu name %}

djangoerp/themes/default/templates/pluggets/plugget_confirm_delete.html
{% extends "base_confirm_delete.html" %}

{% load breadcrumbs %}

{% block breadcrumbs %}
    {% add_crumb 'Home' '/' %}
    {% add_crumb object.region object.region.get_absolute_url %}
    {% add_crumb object.title object.get_absolute_url %}
    {% add_crumb 'Delete' %}
{% endblock %}

{% block object-title %}{{ object.title|striptags|capfirst }}{% endblock %}

djangoerp/themes/default/templates/pluggets/plugget_wizard_form.html
{% extends "base_wizard_form.html" %}

{% load i18n %}
{% load breadcrumbs %}

{% block breadcrumbs %}
    {% add_crumb 'Home' '/' %}
    {% add_crumb region region.get_absolute_url %}
    {% if object and object.pk %}
    {% add_crumb  object.title object.get_absolute_url %}
    {% add_crumb 'Edit' %}
    {% else %}
    {% add_crumb 'Add plugget' %}
    {% endif %}
{% endblock %}

{% block object-title %}
{% if object and object.pk %}
{{ object.title|striptags|capfirst }}
{% else %}
{% blocktrans with model="plugget" %}Add {{ model }}{% endblocktrans %}
{% endif %}
{% endblock %}

{% block subtitle %}
{% blocktrans with step1=wizard.steps.step1 count=wizard.steps.count %}Step {{ step1 }} of {{ count }}:{% endblocktrans %}
{% if wizard.steps.step0 == 0 %}{% trans "choose type" %}{% else %}{% trans "configure settings" %}{% endif %}
{% endblock %}

{% block formbody %}
{{ block.super }}
{% if plugget_description %}
<tr><th>{% trans "Description" %}:</th><td>{{ plugget_description }}</td></tr>
{% endif %}
{% endblock %}

djangoerp/themes/default/templates/pluggets/powered-by.html
{% load i18n %}

<p class="powered-by">{% blocktrans %}Powered by <a href="{{ url }}">{{ name }}</a>{% endblocktrans %}</p>

djangoerp/themes/default/templates/pluggets/region.html
{% load regions %}

{% block region-header %}
<div class="region" id="{{ region.slug }}-region">
{% endblock %}
    
    {% block region-pluggets %}
    {% for p in region.pluggets.all %}
    {% with plugget_index=forloop.counter0 %}
    {% render_plugget p.pk %}
    {% endwith %}
    {% endfor %}
    {% endblock %}
    
{% block region-footer %}
</div>
{% endblock %}