djangoerp/core/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'


from django.conf.urls import url
from django.views.generic import TemplateView

from .views import *


urlpatterns = [

    # User authentication management.
    url(r'^users/login/$', 'django.contrib.auth.views.login', {'template_name': 'auth/login.html'}, name='user_login'),
    url(r'^users/logout/$', view='django.contrib.auth.views.logout_then_login', name='user_logout'),
    url(r'^users/(?P<pk>\d+)/$', view=DetailUserView.as_view(), name='user_detail'),
    url(r'^users/(?P<pk>\d+)/edit/$', view=UpdateUserView.as_view(), name='user_edit'),
    url(r'^users/(?P<pk>\d+)/delete/$', view=DeleteUserView.as_view(), name='user_delete'),
    
    # Homepage.
    url(r'^$', TemplateView.as_view(template_name="index.html")),
]

djangoerp/menus/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'

from django.conf.urls import *

from .views import *

urlpatterns = [

    url(r'^bookmarks/$', view=ListBookmarkView.as_view(), name='bookmark_list'),
    url(r'^bookmarks/add/$', view=CreateBookmarkView.as_view(), name='bookmark_add'),
    url(r'^bookmarks/(?P<slug>[-\w]+)/edit/$', view=UpdateBookmarkView.as_view(), name='bookmark_edit'),
    url(r'^bookmarks/(?P<slug>[-\w]+)/delete/$', view=DeleteBookmarkView.as_view(), name='bookmark_delete'),
]

djangoerp/pluggets/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'


from django.conf.urls import url

from .views import *


urlpatterns = [

    url(r'^pluggets/add/(?P<slug>[-\w]+)/$', view=PluggetWizard.as_view(PluggetWizard.DEFAULT_FORMS), name='plugget_add'),
    url(r'^pluggets/(?P<pk>[\d]+)/edit/$', view=PluggetWizard.as_view(PluggetWizard.DEFAULT_FORMS), name='plugget_edit'),
    url(r'^pluggets/(?P<pk>[\d]+)/delete/$', view=DeletePluggetView.as_view(), name='plugget_delete'),
]

djangoerp/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'


from django.conf.urls import url, include
from django.conf import settings
from django.apps import apps as app_registry


urlpatterns = []


def has_urls(app):
    if app:
        try:
            return getattr(app, 'urls', None) or  __import__("%s.urls" % app.name, {}, {}, ["*"])
        except ImportError:
            pass
    return False


# Basic URL patterns bootstrap.
if 'django.contrib.admin' in settings.INSTALLED_APPS:
    if 'django.contrib.admindocs' in settings.INSTALLED_APPS:
        urlpatterns += [
            url(r'^admin/doc/', include('django.contrib.admindocs.urls'))
        ]
    from django.contrib import admin
    admin.autodiscover()
    urlpatterns += [
        url(r'^admin/', include(admin.site.urls))
    ]

if 'django.contrib.staticfiles' in settings.INSTALLED_APPS:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()


urlpatterns += [url(r'^', include('%s.urls' % app.name)) for app in app_registry.get_app_configs() if has_urls(app)]

djangoerp/notifications/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""This file is part of the django ERP project.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

__author__ = 'Emanuele Bertoldi <emanuele.bertoldi@gmail.com>'
__copyright__ = 'Copyright (c) 2013-2015, django ERP Team'
__version__ = '0.0.5'

import hashlib, json
from datetime import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.template.loader import render_to_string
from djangoerp.core.models import validate_json
from djangoerp.core.utils.rendering import field_to_string

from .managers import *


@python_2_unicode_compatible
class FollowRelation(models.Model):
    """It represents a relation  model between a watcher and a watched object.
    """
    followed_content_type = models.ForeignKey(ContentType, related_name="+")
    followed_id = models.PositiveIntegerField()
    followed = GenericForeignKey('followed_content_type', 'followed_id')
    follower_content_type = models.ForeignKey(ContentType, related_name="+")
    follower_id = models.PositiveIntegerField()
    follower = GenericForeignKey('follower_content_type', 'follower_id')

    objects = FollowRelationManager()
    
    class Meta:
        verbose_name = _('follow relation')
        verbose_name_plural = _('follow relations')

    def __str__(self):
        return _("%s followed by %s") % (self.followed, self.follower)

@python_2_unicode_compatible
class Signature(models.Model):
    """It represents the identifier of an activity and/or a notification.
    """
    title = models.CharField(_('title'), max_length=100)
    slug = models.SlugField(_('slug'), max_length=100, unique=True)

    class Meta:
        verbose_name = _('signature')
        verbose_name_plural = _('signatures')

    def __str__(self):
        return self.title
        
    def save(self, *args, **kwargs):
        if self.slug and not self.title:
            from django.forms.forms import BoundField, pretty_name
            self.title = pretty_name(self.slug).replace("-", " ").capitalize()
        super(Signature, self).save(*args, **kwargs)
 
@python_2_unicode_compatible       
class Subscription(models.Model):
    """A Subscription allows a per-signature-based filtering of notifications.
    """
    subscriber_content_type = models.ForeignKey(ContentType, related_name="+")
    subscriber_id = models.PositiveIntegerField()
    subscriber = GenericForeignKey('subscriber_content_type', 'subscriber_id')
    signature = models.ForeignKey(Signature)
    send_email = models.BooleanField(default=True, verbose_name=_('send email'))
    email = models.EmailField(null=True, blank=True, verbose_name=_('email'))

    objects = SubscriptionManager()

    class Meta:
        verbose_name = _('subscription')
        verbose_name_plural = _('subscriptions')

    def __str__(self):
        return "%s | %s" % (self.subscriber, self.signature)

@python_2_unicode_compatible
class Activity(models.Model):
    """An activity is a registered event that happens at a specific time.
    
    It can be notified by many notifications to many watcher objects.
    """
    title = models.CharField(_('title'), max_length=200)
    signature = models.CharField(_('signature'), max_length=50)
    template = models.CharField(_('template'), blank=True, null=True, max_length=200, default=None)
    context = models.TextField(_('context'), blank=True, null=True, validators=[validate_json], help_text=_('Use the JSON syntax.'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('created'))
    backlink = models.CharField(_('backlink'), blank=True, null=True, max_length=200)
    source_content_type = models.ForeignKey(ContentType, related_name="+")
    source_id = models.PositiveIntegerField()
    source = GenericForeignKey('source_content_type', 'source_id')

    objects = ActivityManager()
    
    class Meta:
        verbose_name = _('activity')
        verbose_name_plural = _('activities')
        ordering = ('-created',)

    def __str__(self):
        try:
            return self.title % self.get_context()
        except KeyError:
            return self.title

    def get_context(self):
        return json.loads(str(self.context or "{}"))
        
    def get_template_name(self):
        return self.template or "notifications/activities/%s.html" % self.signature

    def get_content(self):
        from django.template import TemplateDoesNotExist
        try:
            return render_to_string(self.get_template_name(), self.get_context())
        except: # Catching all exceptions avoid any rendering issue.
            return ""
        
    def get_absolute_url(self):
        return self.backlink or ""

python_2_unicode_compatible
class Notification(models.Model):
    """A notification notifies a specific event to a specific target.
    """
    title = models.CharField(max_length=100, verbose_name=_('title'))
    description = models.TextField(blank=True, null=True, verbose_name=_('description'))
    target_content_type = models.ForeignKey(ContentType, related_name="+")
    target_id = models.PositiveIntegerField()
    target = GenericForeignKey('target_content_type', 'target_id')
    signature = models.ForeignKey(Signature, verbose_name=_('signature'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=_('created on'))
    read = models.DateTimeField(blank=True, null=True, verbose_name=_('read on'))
    dispatch_uid = models.CharField(max_length=32, verbose_name=_('dispatch UID'))

    objects = NotificationManager()

    class Meta:
        verbose_name = _('notification')
        verbose_name_plural = _('notifications')
        ordering = ('-created', 'id')
        get_latest_by = '-created'
        unique_together = (
            ("target_content_type", "target_id", "dispatch_uid"),
        )
        index_together = (
            ("target_content_type", "target_id", "dispatch_uid"),
        )

    def __str__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('notification_detail', (), {"object_model": self.target._meta.verbose_name_plural, "object_id": self.target.pk, "pk": self.pk})

    @models.permalink
    def get_delete_url(self):
        return ('notification_delete', (), {"object_model": self.target._meta.verbose_name_plural, "object_id": self.target.pk, "pk": self.pk})

    def clean_fields(self, exclude=None):
        if not self.dispatch_uid:
            token = "%s%s%s" % (self.title, self.description, datetime.now())
            self.dispatch_uid = hashlib.md5(token.encode('utf-8')).hexdigest()
        """if not Subscription.objects.filter(subscriber=self.target, signature=self.signature):
            raise ValidationError('The target is not subscribed for this kind of notification.')"""
        super(Notification, self).clean_fields(exclude)

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Notification, self).save(*args, **kwargs)

class Observable(object):
    """Mix-in that sends a special signal when a field is changed.
    
    It also offers a simple API to manage followers.
    """
    __change_exclude = []
    __subscriber_fields = []
    
    def __init__(self, *args, **kwargs):
        super(Observable, self).__init__(*args, **kwargs)
        self.__changes = {}
        self.__field_cache = dict([(f.attname, f) for f in (self._meta.fields)])
        self.__followers_cache = None

    def __setattr__(self, name, value):
        try:
            if self.pk and name in self.__field_cache:
                field = self.__field_cache[name]
                label = "%s" % field.verbose_name
                if name not in self.__change_exclude:
                    old_value = field_to_string(field, self)
                    if label in self.__changes:
                        old_value = self.__changes[label][0]
                    super(Observable, self).__setattr__(name, value)
                    value = field_to_string(field, self)
                    if value != old_value:
                        self.__changes[label] = ("%s" % old_value, "%s" % value)
                return

        except:
            pass
        
        super(Observable, self).__setattr__(name, value)

    def followers(self):
        """Returns the list of the current followers.
        """
        if self.__followers_cache:
            return self.__followers_cache
        return [r.follower for r in FollowRelation.objects.filter(followed=self)]
        
    def is_followed_by(self, followers):  
        """Checks if all given instances are followers of this object.
        """      
        if not isinstance(followers, (tuple, list)):
            followers = [followers]
            
        cache_followers = self.followers()
        
        for follower in followers:
            found = False
            for cache_follower in cache_followers:
                if follower == cache_follower:
                    found = True
            if not found:
                return False
                
        return True

    def add_followers(self, followers):
        """Registers the given followers.
        """
        if not isinstance(followers, (tuple, list)):
            followers = [followers]

djangoerp/themes/default/templates/elements/breadcrumbs.html
{% load i18n %}

{% for crumb, link in breadcrumbs %}
    <span class="entry">{% if link %}<a href='{{ link }}' title='{% trans crumb %}'>{% trans crumb %}</a>{% else %}{% trans crumb %}{% endif %}</span>
    {% if not forloop.last %}
    <span class="separator">&raquo;</span>
    {% endif %}
{% endfor %}

djangoerp/themes/default/templates/elements/cancel_button.html
{% load i18n %}
{% load markup %}

{% with index=request.path|slice:':-1'|split:'/'|slice:':-1'|join:'/' %}
{% if object.pk and object.get_absolute_url %}
<span class="cancel"><a title="{% trans 'Cancel' %}" href="{{ back|default:object.get_absolute_url|default:index|default:'/' }}">{% trans "Cancel" %}</a></span>
{% else %}
<span class="cancel"><a title="{% trans 'Cancel' %}" href="{{ back|default:index|default:'/' }}">{% trans "Cancel" %}</a></span>
{% endif %}
{% endwith %}

djangoerp/themes/default/templates/elements/empty.html
{% load i18n %}

<span class="empty">{% trans "Empty" %}</span>

djangoerp/themes/default/templates/elements/link.html
{% load i18n %}

<a href="{{ url }}">{{ caption }}</a>

djangoerp/themes/default/templates/elements/messages.html
{% if messages %}
<ul>
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

djangoerp/themes/default/templates/elements/model_details.html
{% load markup %}

{% for row in details.layout %}
<tr>
    {% with col_size=row|length %}
    {% for col in row %}
    <th>{{ col.name|capfirst }}</th>
    <td{% if forloop.last and col_size < details.num_cols %}{% with col_diff=details.num_cols|diff:col_size %} colspan="{{ col_diff|add:col_diff|add:1 }}"{% endwith %}{% endif %}{{ col.attrs }}>
        {{ col.value }}
    </td>
    {% endfor %}
    {% endwith %}
</tr>
{% endfor %}

djangoerp/themes/default/templates/elements/model_list.html
{% extends "elements/table_list.html" %}

{% load i18n %}
{% load markup %}
{% load introspection %}

{% block table_headers %}
{{ block.super }}

    {% block table_filterbox %}
    <tr class="filterbox">
        {% for h in table.headers %}
        {% join '_' table.uid 'filter_by' h.attname as filter_by_key %}
        {% join '_' table.uid 'filter_expr' h.attname as filter_expr_key %}
        {% block table_field_filter %}
        <td class="{{ h.attname }}-filter">
            {% if h.type == "boolean" %}
            <select title="{% trans 'Select a filter value' %}" name="{{ filter_by_key }}" />
                <option value=""{% if h.filter.value == None %} selected="selected"{% endif %}></option>
                <option value="1"{% if h.filter.value == "1" %} selected="selected"{% endif %}>{% trans "True" %}</option>
                <option value="0"{% if h.filter.value == "0" %} selected="selected"{% endif %}>{% trans "False" %}</option>
            </select>
            {% elif h.type == "foreignkey" %}
            <select title="{% trans 'Select a filter value' %}" name="{{ filter_by_key }}" />
                <option value=""{% if h.filter.value == None %} selected="selected"{% endif %}></option>
                {% with fk_name=h.attname|slice:":-3" %}
                {% for object in unfiltered_object_list %}
                {% with fkobj=object|get:fk_name %}
                {% with fk=fkobj.pk %}
                {% ifchanged fkobj %}
                <option value="{{ fk }}"{% if h.filter.value == fk|safe %} selected="selected"{% endif %}>{{ fkobj }}</option>
                {% endifchanged %}
                {% endwith %}
                {% endwith %}
                {% endfor %}
                {% endwith %}
            </select>
            {% else %}
            <select title="{% trans 'Select a filter criteria' %}" class="expr" name="{{ filter_expr_key }}" />
                <option value=""></option>
                <option value="iexact"{% if h.filter.expr == "iexact" or not h.filter.expr %} selected="selected"{% endif %}>&#61</option>
                <option value="gt"{% if h.filter.expr == "gt" %} selected="selected"{% endif %}>&gt</option>
                <option value="gte"{% if h.filter.expr == "gte" %} selected="selected"{% endif %}>&gt&#61</option>
                <option value="lt"{% if h.filter.expr == "lt" %} selected="selected"{% endif %}>&lt</option>
                <option value="lte"{% if h.filter.expr == "lte" %} selected="selected"{% endif %}>&lt&#61</option>
                <option value="icontains"{% if h.filter.expr == "icontains" %} selected="selected"{% endif %}>{% trans "Has" %}</option>
                <option value="istartswith"{% if h.filter.expr == "istartswith" %} selected="selected"{% endif %}>{% trans "Starts" %}</option>
                <option value="iendswith"{% if h.filter.expr == "iendswith" %} selected="selected"{% endif %}>{% trans "Ends" %}</option>
            </select>
            {% if h.type == "datetime" %}
            <input title="{% trans 'Type a filter date/time' %}" name="{{ filter_by_key }}" type="text" placeholder="{% trans 'YYYY-MM-DD HH:MM' %}" value="{{ h.filter.value }}" />
            {% else %}
            <input title="{% trans 'Type a filter pattern' %}" name="{{ filter_by_key }}" type="text" placeholder="{% trans '...' %}" value="{{ h.filter.value }}" />
            {% endif %}
            {% endif %}
        </td>
        {% endblock %}
        {% endfor %}
        <td>
            <ul class="actions">
                {% join '_' table.uid 'filter' as filter_button_name %}
                {% join '_' table.uid 'reset_filters' as reset_filters_button_name %}
                <li class="search"><button title="{% trans 'Filter' %}" name="{{ filter_button_name }}">{% trans "Filter" %}</button></li>
                <li class="list"><button title="{% trans 'Reset' %}" name="{{ reset_filters_button_name }}">{% trans "Reset" %}</button></li>
            </ul>
        </td>
    </tr>
    {% endblock %}
    
{% endblock %}

{% block table_first_column %}
{% if forloop.counter0 == 0 %}
<input title="{% trans 'Select this item' %}" name="{% if table.uid %}{{ table.uid }}_{% endif %}select_{{ row.object.pk }}" type="checkbox" />
<a title="{{ f }}" href="{{ row.object.get_absolute_url }}">{{ f }}</a>
{% else %}
{{ block.super }}
{% endif %}
{% endblock %}

{% block table_field_actions %}
<ul class="actions">
    {% if row.object.get_edit_url %}<li class="edit"><a title="{% trans 'Edit' %}" href="{{ row.object.get_edit_url }}">{% trans "Edit" %}</a></li>{% endif %}
    {% if row.object.get_delete_url %}<li class="delete"><a title="{% trans 'Delete' %}" href="{{ row.object.get_delete_url }}">{% trans "Delete" %}</a></li>{% endif %}
</ul>
{% endblock %}

{% block table_footer %}
{% if row_count %}
<tfoot>
    <tr>
        <td>
            <input title="{% trans 'Select all' %}" name="{% if table.uid %}{{ table.uid }}_{% endif %}select_all" type="checkbox" />
            <strong>{% blocktrans with row_count=table.rows|length total_count=paginator.count %}All ({{ row_count }} of {{ total_count }} items){% endblocktrans %}</strong>
        </td>
        {% if field_count > 1 %}
        <td colspan="{{ field_count|add:'-1' }}"></td>
        {% endif %}
        <td>
            {% block table_list_actions %}
            <ul class="actions">
                <li class="delete"><button title="{% trans 'Delete selected' %}" name="{% if table.uid %}{{ table.uid }}_{% endif %}delete_selected">{% trans "Delete" %}</button></li>
            </ul>
            {% endblock %}
        </td>
    </tr>
</tfoot>
{% else %}
{{ block.super }}
{% endif %}
{% endblock %}

djangoerp/themes/default/templates/elements/no.html
{% load i18n %}

<span class="no">{% trans "No" %}</span>

djangoerp/themes/default/templates/elements/paginator.html
{% load i18n %}

<div class="paginator">
    <span class="first">
        {% if page_obj.has_previous %}
        <a title="{% trans 'First page' %}" href="{{ request.path }}?{% for k, v in request.GET.items %}{% if k != page_key|default:'page' %}{{ k }}={{ v }};{% endif %}{% endfor %}{{ page_key|default:'page' }}=1">
            <span>&lt;&lt;</span>
        </a>
        {% else %}
        <span class="disabled">&lt;&lt;</span>
        {% endif %}
    </span>

    <span class="previous">
        {% if page_obj.has_previous %}
        <a title="{% trans 'Previous page' %}" href="{{ request.path }}?{% for k, v in request.GET.items %}{% if k != page_key|default:'page' %}{{ k }}={{ v }};{% endif %}{% endfor %}{{ page_key|default:'page' }}={{ page_obj.previous_page_number }}">
            <span>&lt;</span>
        </a>
        {% else %}
        <span class="disabled">&lt;</span>
        {% endif %}
    </span>
    
    <span class="current">
        {% with number=page_obj.number|default:1 num_pages=paginator.num_pages|default:1 %}
        {% blocktrans %}Page {{ number }} of {{ num_pages }}{% endblocktrans %}
        {% endwith %}
    </span>
    
    <span class="next">
        {% if page_obj.has_next %}
        <a title="{% trans 'Next page' %}" href="{{ request.path }}?{% for k, v in request.GET.items %}{% if k != page_key|default:'page' %}{{ k }}={{ v }};{% endif %}{% endfor %}{{ page_key|default:'page' }}={{ page_obj.next_page_number }}">
            <span>&gt;</span>
        </a>
        {% else %}
        <span class="disabled">&gt;</span>
        {% endif %}
    </span>
    
    <span class="last">
        {% if page_obj.has_next %}
        <a title="{% trans 'Last page' %}" href="{{ request.path }}?{% for k, v in request.GET.items %}{% if k != page_key|default:'page' %}{{ k }}={{ v }};{% endif %}{% endfor %}{{ page_key|default:'page' }}={{ paginator.num_pages }}">
            <span>&gt;&gt;</span>
        </a>
        {% else %}
        <span class="disabled">&gt;&gt;</span>
        {% endif %}
    </span>
</div>

djangoerp/themes/default/templates/elements/submit_button.html
{% load i18n %}

<span class="submit"><button title="{% trans 'Confirm' %}" name="{{ submitbutton_value|default:'submit' }}">{% trans 'Confirm' %}</button></span>

djangoerp/themes/default/templates/elements/user_bookmarks.html
{% load i18n %}
{% load menus %}

{% if user.is_authenticated %}
<ul class="actions">
    <li class="list"><a title="{% trans 'Manage your bookmarks' %}" href="{% url 'bookmark_list' %}">{% trans "Manage bookmarks" %}</a></li>
    <li class="add"><a title="{% trans 'Bookmark this page' %}" href="{% url 'bookmark_add' %}">{% trans "Add bookmark" %}</a></li>
</ul>
{% render_user_bookmarks %}
{% endif %}

djangoerp/themes/default/templates/elements/userarea.html
{% load i18n %}
{% load menus %}

{% if user.is_authenticated %}
<span class="profile">
    <a href="{{ user.get_absolute_url }}"><strong>{{ user }}</strong></a>
    {% with user.notification_set.unread.count as notification_count %}
    <a class="notification-counter" title="{% blocktrans %}{{ notification_count }} unread notification(s){% endblocktrans %}" href="{% url 'notification_list' 'users' user.pk %}">
        {{ notification_count }}
    </a>
    {% endwith %}
</span>
{% render_menu "user_area_logged" %}
{% else %}
{% render_menu "user_area_not_logged" %}
{% endif %}